<?php
/**
 * Test Agent - Local Version
 * Sends test events to localhost SIEM collector
 * Run as: php test-agent-local.php
 */

// Configuration
$SIEM_SERVER = '127.0.0.1';  // Localhost for testing
$SIEM_PORT = 9999;
$AGENT_NAME = 'TEST-PC-001';
$COLLECTION_INTERVAL = 5;    // Send every 5 seconds

echo "========================================\n";
echo "Test Agent - Local Version\n";
echo "========================================\n";
echo "Server: $SIEM_SERVER:$SIEM_PORT\n";
echo "Agent: $AGENT_NAME\n";
echo "Status: Running...\n";
echo "Press Ctrl+C to stop\n\n";

$event_count = 0;

// Main loop
while (true) {
    try {
        // Create test events
        $events = generateTestEvents();
        
        if (!empty($events)) {
            // Send to SIEM collector
            $sent = sendToSIEM($events);
            
            if ($sent) {
                $event_count += count($events);
                echo "[" . date('Y-m-d H:i:s') . "] Sent " . count($events) . " events (Total: $event_count)\n";
            }
        }
        
        // Wait before next collection
        sleep($COLLECTION_INTERVAL);
        
    } catch (Exception $e) {
        echo "[ERROR] " . $e->getMessage() . "\n";
        sleep(5);
    }
}

/**
 * Generate test events
 */
function generateTestEvents() {
    $events = [];
    
    // Simulate different event types
    $event_types = [
        'User-Login',
        'Process-Creation',
        'File-Access',
        'Network-Connection',
        'Service-Start'
    ];
    
    $severities = ['info', 'low', 'medium', 'high', 'critical'];
    
    // Generate 2-5 random events
    $count = rand(2, 5);
    
    for ($i = 0; $i < $count; $i++) {
        $event = [
            'agent_name' => 'TEST-PC-001',
            'event_type' => $event_types[array_rand($event_types)],
            'severity' => $severities[array_rand($severities)],
            'source_ip' => '192.168.1.' . rand(10, 200),
            'destination_ip' => '192.168.1.' . rand(10, 200),
            'source_port' => rand(1024, 65535),
            'destination_port' => rand(1, 1024),
            'message' => 'Test event generated by test agent',
            'timestamp' => date('Y-m-d H:i:s'),
            'user_account' => 'TESTUSER',
            'process_name' => 'test-process.exe',
            'protocol' => ['TCP', 'UDP'][rand(0, 1)]
        ];
        
        $events[] = $event;
    }
    
    return $events;
}

/**
 * Send events to SIEM collector
 */
function sendToSIEM($events) {
    global $SIEM_SERVER, $SIEM_PORT;
    
    try {
        // Connect to SIEM collector
        $socket = @fsockopen($SIEM_SERVER, $SIEM_PORT, $errno, $errstr, 5);
        
        if (!$socket) {
            echo "[DEBUG] Connection failed: $errstr ($errno)\n";
            return false;
        }
        
        echo "[DEBUG] Connected to $SIEM_SERVER:$SIEM_PORT\n";
        
        // Send all events at once
        $data = '';
        foreach ($events as $event) {
            $data .= json_encode($event) . "\n";
        }
        
        echo "[DEBUG] Sending " . strlen($data) . " bytes\n";
        
        // Send data
        $bytes = fwrite($socket, $data);
        
        if ($bytes === false) {
            echo "[DEBUG] Write failed\n";
            fclose($socket);
            return false;
        }
        
        echo "[DEBUG] Wrote $bytes bytes\n";
        
        // Wait a moment for server to process
        sleep(1);
        
        fclose($socket);
        return true;
        
    } catch (Exception $e) {
        echo "[ERROR] " . $e->getMessage() . "\n";
        return false;
    }
}

?>
